version: "3.9"
services:
  api:
    image: python:3.12-slim
    working_dir: /app
    command: bash -lc "pip install -r app/requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=postgresql+psycopg://rmm:rmm@db:5432/rmm
      - REDIS_HOST=redis
      - ADMIN_TOKEN=supersecretadmin
      - SLACK_WEBHOOK_URL=
    ports:
      - "8000:8000"
    depends_on: [db, redis]
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=rmm
      - POSTGRES_PASSWORD=rmm
      - POSTGRES_DB=rmm
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  dbdata:
